#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDgzJOxpZuh4N0KDcOq+To+oBPr8kmp69GMDb0qI2t5t asshadrunov@miem.hse.ru

runcmd:
  - cd /home/user
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sudo sh get-docker.sh
  - sudo docker run -d --cap-add=NET_ADMIN -p 1194:1194/udp -p 80:8080/tcp -e HOST_ADDR=$(curl -s https://api.ipify.org) --name dockovpn alekslitvinenk/openvpn
  - sudo docker logs dockovpn > logs.txt
  - wget http://localhost/ -o client.ovpn