phantom:
  address: 130.193.53.214:80 # [Target's address]:[target's port]
  load_profile:
    load_type: rps # schedule load by defining requests per second
    schedule: line(1, 600, 15m) # starting from 1rps growing linearly to 10rps during 10 minutes
console:
  enabled: true # enable console output
telegraf:
  enabled: false # let's disable telegraf monitoring for the first time
